name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install EAS CLI
        run: npm i -g eas-cli

      - name: Install deps
        run: npm ci

      - name: Build APK (EAS)
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: eas build --platform android --profile preview --non-interactive --local --output build.apk || eas build --platform android --profile preview --non-interactive

      - name: Upload artifact (local)
        if: exists('build.apk')
        uses: actions/upload-artifact@v4
        with:
          name: app-preview-apk
          path: build.apk

